[colors]
background = '#141218'
foreground = '#e6e0e9'

cursor_bg = '#d0bcff'
cursor_fg = '#141218'
cursor_border = '#d0bcff'

selection_bg = '#4f378b'
selection_fg = '#e6e0e9'

ansi = ['#141218', '#ff728f', '#7fff9a', '#ffda72', '#bca5f2', '#4e3d76', '#D0BCFF', '#f4efff']
brights = ['#9d99a5', '#ff9fb2', '#a5ffb8', '#ffe7a5', '#d7c6ff', '#ded0ff', '#e9e0ff', '#faf8ff']
